[phases.setup]
nixPkgs = ['python311']
aptPkgs = ['libgl1-mesa-glx', 'libglib2.0-0', 'libsm6', 'libxext6', 'libxrender-dev', 'libgomp1']]

[phases.install]
cmds = [
    'pip install --no-cache-dir -r requirements.txt'
]

[start]
cmd = 'gunicorn yolo:app --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120 --worker-class gthread --max-requests 100 --max-requests-jitter 10'
