[phases.setup]
nixPkgs = ['python311']

[phases.install]
cmds = [
  'pip install --upgrade pip',
  'pip install --no-cache-dir torch torchvision --index-url https://download.pytorch.org/whl/cpu',
  'pip install --no-cache-dir -r requirements.txt'
]

[start]
cmd = 'gunicorn yolo:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1'
